project:
  type: manuscript
  render:
  - "*.qmd"
  - "!TODO.md"
  - "!README.md"
  - "develop/"
execute:
  freeze: auto

format:
  html:
    notebook-links: global
    notebook-view: false
    toc: true
    toc-depth: 5
    comments:
      hypothesis: true
  # docx: default
  # jats: default
  # aft-pdf:
  #   notebook-links: global
  #   notebook-view: false
  #   default:
  #     keep-tex: true
  pdf:
    prefer-html: true
    notebook-links: global
    notebook-view: false
    default:
      keep-tex: true
    